### PR TITLE
file for extracting the meta-issues on github.

### PR DESCRIPTION
**Pull request by iharshit009**

### CODE REVIEW

**Comment by iharshit009** [comment]
@nelsonic  sir I could not identify a way to resolve the checks raised by Travis-ci ..
Could you please guide me to work on it??

**Comment by iharshit009** [comment]
@nelsonic sorry sir I am currently having no knowledge of jQuery and javascript ..

**Comment by nelsonic** [comment]
@iharshit009 I _agree_ that it makes sense to focus on Python for ML. 👍

**Comment by iharshit009** [comment]
sir i will definately try to get back soon with some hands on js and
jquery..  Sir are there any project you are working on python or can you
reference me to any other projects to start me towards open source
contributions??

**Comment by nelsonic** [comment]
@iharshit009 your best bet is to focus on your Python ML skills for now.
We will be doing a Computer Vision project _very_ soon and I will ping you when there is something to see. 👍

**Pull request closed without merging**
