### PR TITLE
Fix minor typo in readme file

### PR DESCRIPTION
**Pull request by jinjorge**
Awesome repo :+1:

### CODE REVIEW

**Comment by nelsonic** [comment]
well spotted. thanks for fixing. :+1:

**Comment by nelsonic** [comment]
@jinjorge *annoyingly* one of the tests needs to be updated...
see: https://travis-ci.org/nelsonic/github-scraper/builds/95630818#L1358

If you have a minute to "fix" it, [Line 14 of /test/repo.test.js](https://github.com/nelsonic/github-scraper/blob/040e341697840e79f813db6e0195899e9a88d572/test/repo.test.js#L14) needs to be changed to:
```js
 t.ok(stats.langs[0].indexOf('HTML') > -1, 'Language is: '+ stats.langs);
```
Let me know if you have :hourglass_flowing_sand: 
thanks again!

**Comment by jinjorge** [comment]
@nelsonic will do. Going to also removed the commented out lines in the code

**Comment by jinjorge** [comment]
no bueno :(

Investigating....

**Comment by jinjorge** [comment]
my bad... wrong branch. Fixing shortly

**Comment by jinjorge** [comment]
sorry... this is ugly. feel free to close it and I'll fix it in a new PR

**Comment by jinjorge** [comment]
fixed it here https://github.com/nelsonic/github-scraper/pull/64

**Pull request closed without merging**
