### PR TITLE
Ui update repo

### PR DESCRIPTION
**Pull request by abakermi**
#113   fix repo/repos ui updates

### CODE REVIEW

**Comment by nelsonic** [comment]
Hi @abakermi thanks for creating this PR. 🙌 
You have done a good job of moving the code toward better modularity/maintainability. 👍 
Curious why Travis-CI https://travis-ci.org/github/nelsonic/github-scraper is not passing ... 💭 
Might need to update a couple of the tests/assertions. 💡

**Comment by abakermi** [comment]
hi @nelsonic  ,Travis-CI won't pass unless we update the rest of tests, I just update repo/repos

**Comment by nelsonic** [comment]
Looks like it's only _one_ test: https://travis-ci.org/github/nelsonic/github-scraper/builds/711131428#L613
image

> **Note**: I _definitely_ would not _normally_ tell anyone to comment out tests, but in this case it's "OK" because the underlying UI has changed so the tests will _continue_ to fail until the selector is updated. 

Please comment out the line: 
https://github.com/nelsonic/github-scraper/blob/47d0a460db49b5ea3067ce4eb1d4e6bc27b7f505/test/followers.test.js#L7

And see if the rest of the tests pass. 
Thanks. ☀️

**Comment by abakermi** [comment]
I suspect thats one test failt , anyway i will update the rest of the test and push again .

**Comment by nelsonic** [comment]
Thanks! 👍 
Out of curiosity: how did you _find_ this repo? (_what did you search for?_) 🔍 
And how are you hiding stats on your GitHub profile? 🚫  (_is that a new option they have added recently_?)

**Comment by abakermi** [comment]
hhh I don't hide my stats, just I don't have time to contribute, and for repos I see issuehub.io

**Comment by nelsonic** [comment]
I mean these "profile" stats ... this is what I see: (_no stars or follower count_) 🤷‍♂️ 
image

But I just checked in incognito mode and they are visible. 👍 
GitHub must be A-B testing on me 🙄 

Thanks for sharing the link to http://issuehub.io 🔗

**Review by nelsonic — APPROVED** [review]
Thanks @abakermi 👌

**Pull request merged**
